# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = database/alembic

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date
# within the migration file as well as the filename.
# string value is passed to dateutil.tz.gettz()
# leave blank for localtime
timezone = UTC

# max length of characters to apply to the
# "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment file as a
# standalone script, false to use exec() it
# (see docs for more info)
# run_environment_as_script = false

# set to 'true' to force empty revision to have a file
# even if there are no changes to the schema
# see docs for more info
# revision_environment = false

# set to 'true' to autogenerate revision on empty revision
# see docs for more info
# autogenerate_revision_on_empty = false

# logging configuration
[logging]
# The format of the log records.
# Each record is on a single line, with a logger name, a level and a message.
# The logger name is padded to 20 characters, the level to 8 characters.
# format = %(name)-20s %(levelname)-8s %(message)s

# The default logging level.
# level = INFO

# The name of the log file. If not specified, logging will go to the console.
# log_file = alembic.log

[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts. See the documentation for further
# detail and examples

# keys are script names, values are functions to execute
# update_models = database.alembic:update_models

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic
qualname =

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S